Translate agents page
langchain-contribution/langchainjs pull request #13
Opened 2023-07-01 09:05 UTC by tmdgusya

2023-07-04 14:12 UTC, sigridjineth requested changes
수고하셨습니당 몇 가지 수정 필요사항을 적어드렸습니다.

2023-07-04 14:12 UTC, sigridjineth commented on docs/docs/modules/agents/agents/examples/conversational_agent.mdx
> +    "action_input": "안녕 Bob! 오늘은 어떻게 도와드릴까요?"
여기서는 바꾸지 않아도 되겠지만, 앞으로는 굳이 이런 것 까지는 번역하지 않아도 될 것 같습니다. 시스템 메시지라서요.

2023-07-04 14:12 UTC, sigridjineth commented on docs/docs/modules/agents/agents/examples/custom_agent_chat.mdx
> +이 예시는 어떻게 chat model 을 위해 커스텀 에이전트를 생성하는지를 다룹니다. 이는 chat 특화된 prompt 를 사용할 것입니다.
한국어와 영어가 혼합될 때는 영어 단어는 대문자로 표현해주는 것이 가독성에 더 좋다는 개인적인 의견 드립니다.
(e.g. `Chat에 특화된 Prompt를 사용할 것입니다.`)

2023-07-04 14:12 UTC, sigridjineth commented on docs/docs/modules/agents/agents/index.mdx
> +이 에이전트는 MRKL 과 같은 에이전트 프롬프트 체인을 감싼 stateless wrapper 입니다. 프롬프트 서식도구를 처리하며, 채팅 모델으로 부터오는 응답을 얻어 파싱합니다. 또한 사용자 입력을 받아들이고 취할 "동작"과 해당 "동작 입력"에 해당하는 응답을 반환합니다.
Action을 동작이라고 번역하셨지만 Action 자체를 고유명사로 해석하여 Action / Action Input으로 받아들이면 어떨까 합니다.
마치 우리가 Prompt를 굳이 번역하지 않고 프롬프트 그 자체로 받아들이는 것처럼요.

2023-07-04 14:12 UTC, sigridjineth commented on docs/docs/modules/agents/agents/index.mdx
> +당신이 고를 수 있는 에이전트는 당신이 수행하고자 하는 작업의 종류에 따라 달라집니다. 여기 당신의 사용 사례에 맞는 에이전트를 고르는데 도움이 될만한 빠른 가이드가 있습니다.
당신이라는 어구는 한국어에 맞지 않습니다. 과도한 번역체이므로 빼주세요.

2023-07-04 14:16 UTC, sigridjineth approved these changes

2023-07-05 00:04 UTC, tmdgusya commented on docs/docs/modules/agents/agents/index.mdx
> +당신이 고를 수 있는 에이전트는 당신이 수행하고자 하는 작업의 종류에 따라 달라집니다. 여기 당신의 사용 사례에 맞는 에이전트를 고르는데 도움이 될만한 빠른 가이드가 있습니다.
@sigridjineth 네넵

2023-07-08 04:00 UTC, merged