Translate the vector store section in the indexes page into Korean
langchain-contribution/langchainjs pull request #9
Opened 2023-05-14 08:34 UTC by hyejungg

Translate the vector store section in the indexes page into Korean
- /ko/docs/modules/indexes/vector_stores/
- /ko/docs/modules/indexes/vector_stores/integrations/
- /ko/docs/modules/indexes/vector_stores/integrations/memory
- /ko/docs/modules/indexes/vector_stores/integrations/hnswlib
- /ko/docs/modules/indexes/vector_stores/integrations/milvus
- /ko/docs/modules/indexes/vector_stores/integrations/opensearch
- /ko/docs/modules/indexes/vector_stores/integrations/memory
- /ko/docs/modules/indexes/vector_stores/integrations/pinecone
- /ko/docs/modules/indexes/vector_stores/integrations/prisma
- /ko/docs/modules/indexes/vector_stores/integrations/supabase
- /ko/docs/modules/indexes/vector_stores/integrations/weaviate

2023-05-15 06:04 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/index.mdx
> +벡터 스토어는 documents와 [embeddings](../../models/embeddings/)을 저장한 다음 특정 쿼리에 가장 관련성이 높은 documents, 즉 쿼리의 임베딩과 가장 유사한 embeddings을 가져오는 데 최적화된 특정 유형의 데이터베이스입니다.
문서 라고 해주셔도 될 것 같아요

2023-05-15 06:04 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/index.mdx
> +   * 기존 VectorStore에 Documents 더 추가합니다.
기존 VectorStore에 새로운 Documents를 추가합니다.

2023-05-15 06:05 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/index.mdx
> +   * 고급: 이미 Embeddings 된 데이터가 있는 경우, 기존의 VectorStore 에 Documents 를 추가합니다.
고급 대신 심화?

2023-05-15 06:07 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/index.mdx
> +[Documents](../../schema/document) 목록 또는 텍스트 목록과 메타 데이터에서 VectorStore 를 만들 수 있습니다.
텍스트의 목록과 그 메타 데이터에서 벡터 스토어를 새롭게 만들 수 있습니다
기존의 인덱스로부터 새로운 벡터 스토어를 만들 수 있습니다. 다만 이 방법의 경우 사용하는 벡터 스토어에 따라 메소드 시그쳐가 다르기 때문에 본인이 사용하는 벡터 스토어의 문서를 확인하세요.

2023-05-15 07:04 UTC, sigridjineth requested changes
몇 가지 바꿔주세요.

2023-05-15 07:04 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/integrations/chroma.mdx
> +## Index, query Documents 사용하기
인덱스 및 쿼리 문서 사용하기 정도 괜찮지 않을까요?

2023-05-15 07:04 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/integrations/chroma.mdx
>  <CodeBlock language="typescript">{FromDocs}</CodeBlock>
이런 것은 `FromDocs` 에서 복사해와서 주석을 번역해야 할 지도 고민이네요.

2023-05-15 07:04 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/integrations/opensearch.md
> +[OpenSearch](https://opensearch.org/)는 [Elasticsearch](https://www.elastic.co/elasticsearch/)의 자식(fork) 오픈소스로, Elasticsearch API와 완벽하게 호환됩니다. 이를 이용하여 가장 가까운 근사 검색에 대한 자세한 내용은 [여기](https://opensearch.
자식 보다는 포크한 오픈소스로 가 나을 것 같아요.

2023-05-15 07:04 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/integrations/prisma.mdx
> +Langchain은 PostgreSQL 데이터베이스의 vector 검색을 위해 [Prisma](https://www.prisma.io/) 및 Postgres 확장자와 함께 [`pgvector`](https://github.com/pgvector/pgvector)를 사용하는 것을 지원합니다.
extension은 확장자가 아니라 확장 플러그인 정도로 번역해주시는 것이...

2023-05-15 07:04 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/integrations/supabase.mdx
> +Langchain은 postgres의 확장인 `pgvector` 를 사용하여 Supabase Postgres database 를 VectorStore로 사용할 수 있도록 지원합니다. 자세한 내용은 [Supabase blog post](https://supabase.com/blog/openai-embeddings-postgres-vector)를 참고하세요.
확장인 -> 확장 플러그인인

2023-05-15 07:04 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/integrations/weaviate.mdx
> +Weaviate는 객체와 벡터를 모두 저장하는 오픈소스 벡터 데이터베이스로, 벡터 검색과 구조화된 필터링을 결합할 수 있습니다. LangChain은 Weaviate의 공식 타입스크립트 클라이언트인 [`weaviate-ts-client`](https://weaviate.io/developers/weaviate/client-libraries/typescrip
벡터 검색과 구조화된 필터링 -> 벡터를 검색하고 구조화된 필터링 기능을 적용할 수 있습니다

2023-05-15 07:04 UTC, sigridjineth commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/integrations/weaviate.mdx
> +LangChain은 Weaviate에 직접 벡터를 삽입하고 주어진 벡터의 가장 가까운 이웃을 Weaviate에 쿼리하여 모든 LangChain 임베딩 통합을 Weaviate와 사용할 수 있도록 합니다.
이웃보다는 가까운 벡터 값을

2023-05-20 09:29 UTC, hyejungg commented on docs/i18n/ko/docusaurus-plugin-content-docs/current/modules/indexes/vector_stores/index.mdx
> +벡터 스토어는 documents와 [embeddings](../../models/embeddings/)을 저장한 다음 특정 쿼리에 가장 관련성이 높은 documents, 즉 쿼리의 임베딩과 가장 유사한 embeddings을 가져오는 데 최적화된 특정 유형의 데이터베이스입니다.
벡터 스토어는 문서와 Embedding 을 저장한 다음 ~ 
Vector Store는 Documnets와 Embedding 을 저장한 다음 ~ 
중 뭐가 나을까요?

2023-06-10 08:33 UTC, sigridjineth approved these changes

2023-06-10 08:33 UTC, merged